name: "Create release"

on:
  push:
    branches:
      - releases/*

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Test release
        run: |
          sudo npm install n 
          sudo n latest
          npm test
      - name: Get branch ending
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/} | sed 's:.*/::')"
        id: extract_branch
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          title: New release
          automatic_release_tag: ${{ steps.extract_branch.outputs.branch }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
